 ## Indian Road Accident Dataset (2022–2025)



 The Indian Road Accident Dataset (2022–2025) contains detailed information about road accidents that occurred across various cities and states in India. The dataset includes approximately 20,000 records with multiple features describing different aspects of each accident such as location, time, environmental conditions, and severity.

The dataset consists of both numerical and categorical variables. Numerical columns such as latitude, longitude, temperature, vehicles_involved, casualties, and risk_score provide quantitative insights, while categorical columns like city, state, weather, visibility, traffic_density, cause, and accident_severity describe the nature and conditions of accidents. The dataset also includes date and time-related features such as date, time, hour, day_of_week, and is_weekend, which are useful for time-based analysis.

This dataset is well-suited for Exploratory Data Analysis (EDA) to understand accident patterns, identify high-risk locations, analyze the impact of weather and traffic conditions, and study trends over time. It also enables detection of missing values, data quality issues, and supports feature engineering for deeper insights into accident risk factors.

In [2]:
import pandas as pd
import numpy as np

df=pd.read_csv(r"C:\Users\Lenovo\OneDrive\Desktop\TABLEAU PROJECT DATA\Documents\EDA Project\data\indian_roads_dataset.csv")
df

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,low,32,high,weather,fatal,2,2,0,NaN,0.85
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,high,34,low,weather,major,4,3,0,NaN,0.10
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,low,21,medium,weather,minor,1,1,0,NaN,0.45
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,low,30,high,distraction,minor,5,2,0,NaN,0.65
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,high,24,low,distraction,minor,2,1,0,NaN,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,Bangalore,Karnataka,13.092276,77.599571,2022-09-29,3:00,3,Thursday,0,...,high,31,low,distraction,minor,3,2,0,NaN,0.10
19996,19996,Chennai,Tamil Nadu,13.172928,80.157062,2023-11-25,1:00,1,Saturday,1,...,high,20,low,distraction,major,4,2,0,NaN,0.10
19997,19997,Chennai,Tamil Nadu,12.997170,80.150724,2022-06-18,15:00,15,Saturday,1,...,high,22,low,weather,minor,3,3,0,NaN,0.10
19998,19998,Kolkata,West Bengal,22.454882,88.322213,2023-03-12,4:00,4,Sunday,1,...,high,33,low,poor road,minor,1,0,0,NaN,0.10
19999,19999,Delhi,Delhi,28.510266,77.065301,2024-07-05,23:00,23,Friday,0,...,low,39,high,overspeeding,minor,4,2,0,NaN,0.65

In [3]:
df.head()

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,low,32,high,weather,fatal,2,2,0,NaN,0.85
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,high,34,low,weather,major,4,3,0,NaN,0.10
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,low,21,medium,weather,minor,1,1,0,NaN,0.45
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,low,30,high,distraction,minor,5,2,0,NaN,0.65
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,high,24,low,distraction,minor,2,1,0,NaN,0.10

In [4]:
df.tail()

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
19995,19995,Bangalore,Karnataka,13.092276,77.599571,2022-09-29,3:00,3,Thursday,0,...,high,31,low,distraction,minor,3,2,0,NaN,0.10
19996,19996,Chennai,Tamil Nadu,13.172928,80.157062,2023-11-25,1:00,1,Saturday,1,...,high,20,low,distraction,major,4,2,0,NaN,0.10
19997,19997,Chennai,Tamil Nadu,12.997170,80.150724,2022-06-18,15:00,15,Saturday,1,...,high,22,low,weather,minor,3,3,0,NaN,0.10
19998,19998,Kolkata,West Bengal,22.454882,88.322213,2023-03-12,4:00,4,Sunday,1,...,high,33,low,poor road,minor,1,0,0,NaN,0.10
19999,19999,Delhi,Delhi,28.510266,77.065301,2024-07-05,23:00,23,Friday,0,...,low,39,high,overspeeding,minor,4,2,0,NaN,0.65

In [6]:
df.shape

(20000, 24)

In [8]:
df.columns

Index(['accident_id', 'city', 'state', 'latitude', 'longitude', 'date', 'time',
       'hour', 'day_of_week', 'is_weekend', 'road_type', 'lanes',
       'traffic_signal', 'weather', 'visibility', 'temperature',
       'traffic_density', 'cause', 'accident_severity', 'vehicles_involved',
       'casualties', 'is_peak_hour', 'festival', 'risk_score'],
      dtype='object')

In [9]:
df.info

<bound method DataFrame.info of        accident_id        city        state   latitude  longitude        date  \
0                0        Pune  Maharashtra  18.680827  73.930388  2023-10-22
1                1      Mumbai  Maharashtra  18.817732  72.790846  2023-05-21
2                2      Mumbai  Maharashtra  19.096889  72.819424  2024-07-10
3                3  Chandigarh       Punjab  30.787805  76.847507  2025-03-30
4                4     Chennai   Tamil Nadu  12.965155  80.283313  2024-01-25
...            ...         ...          ...        ...        ...         ...
19995        19995   Bangalore    Karnataka  13.092276  77.599571  2022-09-29
19996        19996     Chennai   Tamil Nadu  13.172928  80.157062  2023-11-25
19997        19997     Chennai   Tamil Nadu  12.997170  80.150724  2022-06-18
19998        19998     Kolkata  West Bengal  22.454882  88.322213  2023-03-12
19999        19999       Delhi        Delhi  28.510266  77.065301  2024-07-05

        time  hour day_of_week  is_weekend  ... visibility  temperature  \
0       5:00     5      Sunday           1  ...        low           32
1       4:00     4      Sunday           1  ...       high           34
2      13:00    13   Wednesday           0  ...        low           21
3      11:00    11      Sunday           1  ...        low           30
4      16:00    16    Thursday           0  ...       high           24
...      ...   ...         ...         ...  ...        ...          ...
19995   3:00     3    Thursday           0  ...       high           31
19996   1:00     1    Saturday           1  ...       high           20
19997  15:00    15    Saturday           1  ...       high           22
19998   4:00     4      Sunday           1  ...       high           33
19999  23:00    23      Friday           0  ...        low           39

       traffic_density         cause accident_severity  vehicles_involved  \
0                 high       weather             fatal                  2
1                  low       weather             major                  4
2               medium       weather             minor                  1
3                 high   distraction             minor                  5
4                  low   distraction             minor                  2
...                ...           ...               ...                ...
19995              low   distraction             minor                  3
19996              low   distraction             major                  4
19997              low       weather             minor                  3
19998              low     poor road             minor                  1
19999             high  overspeeding             minor                  4

      casualties is_peak_hour festival  risk_score
0              2            0      NaN        0.85
1              3            0      NaN        0.10
2              1            0      NaN        0.45
3              2            0      NaN        0.65
4              1            0      NaN        0.10
...          ...          ...      ...         ...
19995          2            0      NaN        0.10
19996          2            0      NaN        0.10
19997          3            0      NaN        0.10
19998          0            0      NaN        0.10
19999          2            0      NaN        0.65

[20000 rows x 24 columns]>

In [42]:
df['date'] = pd.to_datetime(df['date'])    #convert to datetime
df['date']

0        2023
1        2023
2        2024
3        2025
4        2024
         ...
19995    2022
19996    2023
19997    2022
19998    2023
19999    2024
Name: year, Length: 20000, dtype: int32

In [34]:
df.describe()

,accident_id,latitude,longitude,date,hour,is_weekend,lanes,traffic_signal,temperature,vehicles_involved,casualties,is_peak_hour,risk_score
count,20000.000000,20000.000000,20000.000000,20000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,9999.500000,20.389207,78.173330,2023-08-22 07:04:48.000000256,11.487200,0.286150,3.493950,0.499850,27.579600,2.992000,1.726450,0.247400,0.437585
min,0.000000,12.800172,72.700017,2022-01-01 00:00:00,0.000000,0.000000,1.000000,0.000000,15.000000,1.000000,0.000000,0.000000,0.100000
25%,4999.750000,13.198653,73.997979,2022-10-25 00:00:00,5.000000,0.000000,2.000000,0.000000,21.000000,2.000000,1.000000,0.000000,0.250000
50%,9999.500000,18.812008,77.297000,2023-08-21 00:00:00,12.000000,0.000000,4.000000,0.000000,28.000000,3.000000,1.000000,0.000000,0.450000
75%,14999.250000,28.402467,80.111089,2024-06-21 00:00:00,18.000000,1.000000,5.000000,1.000000,34.000000,4.000000,3.000000,0.000000,0.600000
max,19999.000000,30.799960,88.499861,2025-04-15 00:00:00,23.000000,1.000000,6.000000,1.000000,40.000000,5.000000,5.000000,1.000000,1.000000
std,5773.647028,6.165791,4.485967,NaN,6.945563,0.451972,1.705406,0.500012,7.454746,1.415534,1.489104,0.431512,0.218130

In [11]:
df.nunique()

accident_id          20000
city                     8
state                    7
latitude             19907
longitude            19927
date                  1201
time                    24
hour                    24
day_of_week              7
is_weekend               2
road_type                3
lanes                    6
traffic_signal           2
weather                  3
visibility               3
temperature             26
traffic_density          3
cause                    5
accident_severity        3
vehicles_involved        5
casualties               6
is_peak_hour             2
festival                 4
risk_score              18
dtype: int64

In [13]:
#Identify Column Types


num_cols = df.select_dtypes(include=['int64','float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

num_cols, cat_cols

(Index(['accident_id', 'latitude', 'longitude', 'hour', 'is_weekend', 'lanes',
        'traffic_signal', 'temperature', 'vehicles_involved', 'casualties',
        'is_peak_hour', 'risk_score'],
       dtype='object'),
 Index(['city', 'state', 'date', 'time', 'day_of_week', 'road_type', 'weather',
        'visibility', 'traffic_density', 'cause', 'accident_severity',
        'festival'],
       dtype='object'))

In [19]:
df.isnull().sum()

accident_id              0
city                     0
state                    0
latitude                 0
longitude                0
date                     0
time                     0
hour                     0
day_of_week              0
is_weekend               0
road_type                0
lanes                    0
traffic_signal           0
weather                  0
visibility               0
temperature              0
traffic_density          0
cause                    0
accident_severity        0
vehicles_involved        0
casualties               0
is_peak_hour             0
festival             19885
risk_score               0
dtype: int64

In [21]:
df.isnull().sum()

accident_id              0
city                     0
state                    0
latitude                 0
longitude                0
date                     0
time                     0
hour                     0
day_of_week              0
is_weekend               0
road_type                0
lanes                    0
traffic_signal           0
weather                  0
visibility               0
temperature              0
traffic_density          0
cause                    0
accident_severity        0
vehicles_involved        0
casualties               0
is_peak_hour             0
festival             19885
risk_score               0
dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)

## Data Quality Issues

In [ ]:

- Missing values in 'festival'
- Date column converted to datetime
- Need to check duplicates
- Possible inconsistencies in categorical columns
- Outliers may be present in numerical columns